/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class smart_com_jnitest_myJNI */

#ifndef _Included_smart_com_jnitest_myJNI
#define _Included_smart_com_jnitest_myJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     smart_com_jnitest_myJNI
 * Method:    Add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_smart_com_jnitest_myJNI_Add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     smart_com_jnitest_myJNI
 * Method:    Publish_rtmp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_smart_com_jnitest_myJNI_Publish_1rtmp
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
